---
# tasks file for haproxy

- name: Install haproxy and haproxyctl
  ansible.builtin.package:
    name: 
      - haproxy
      - haproxyctl
    state: present

- name: Create group
  ansible.builtin.group:
    name: haproxy
    system: yes
    state: present

- name: Create user
  ansible.builtin.user:
    name: haproxy
    system: yes
    state: present

- name: Create SSL directory
  file:
    path: "{{ haproxy_certdir }}"
    state: directory
    owner: root
    group: root
    mode: '0770'
  when: haproxy_certs is defined

- name: Copy TLS Certificates
  copy:
    src: "{{item}}" 
    dest: "{{ haproxy_certdir }}/{{ item | basename }}"
    owner: root
    group: root
    mode: '0640'
  with_items: "{{ haproxy_certs }}"
  notify:
    - Restart haproxy
  when: haproxy_certs is defined

- name: Set kernel parameter that allows binding nonlocal addresses (VIP IPs)
  ansible.posix.sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: '1'
    state: present

- name: Create HAProxy configuration from template
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    validate: haproxy -c -f %s
    mode: "0640"
  notify:
    - Restart haproxy
  when:
    - ansible_default_ipv4 is defined

- name: Modify selinux settings
  block:
    - name: Add haproxy_stats_port to http_port_t selinux type
      community.general.seport:
        ports: "{{ haproxy_stats_port }}"
        proto: tcp
        setype: http_port_t
        state: present
      when:
        - haproxy_stats_port is defined

    - name: Allow haproxy to open any port
      ansible.posix.seboolean:
        name: haproxy_connect_any
        state: yes
        persistent: yes
      notify:
        - Reboot
  when:
    - ansible_selinux.status is defined
    - ansible_selinux.status == "enabled"

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Start and enable haproxy
  ansible.builtin.service:
    name: haproxy
    state: started
    enabled: yes
